# 此单机版本client配置信息
#eureka:
#  instance:
#    hostname: localhost
#    instance-id: re-app #在eureka 显示的status状态名称
#    prefer-ip-address: true #在点击服务名的时候显示ip地址便于调试
#  client:
#    registerWithEureka: false #向服务注册中心注册自己
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8001/eureka/ #指向注册中心的服务地址


#以下为集群注册
eureka:
  instance:
    hostname: localhost
    instance-id: re-web #在eureka 显示的status状态名称
    prefer-ip-address: true #在点击服务名的时候显示ip地址便于调试
  client:
    registerWithEureka: true #向服务注册中心注册自己
    fetchRegistry: true
    serviceUrl:
      #集群的话有多个就的注册多个
      defaultZone: http://re-netflix.com:8001/eureka/,http://re-netflix1.com:8002/eureka/
